<?php

/**
 * This is the model base class for the table "mail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mail".
 *
 * Columns in table "mail" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $profile_id
 * @property string $to
 * @property string $creation_date
 * @property string $message
 * @property string $log
 *
 */
abstract class BaseMail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mail';
	}

	public static function label($n = 1) {
		return Yii::t('base', 'Mail|Mails', $n);
	}

	public static function representingColumn() {
		return 'to';
	}

	public function rules() {
		return array(
			array('profile_id', 'numerical', 'integerOnly'=>true),
			array('to', 'length', 'max'=>255),
			array('creation_date, message, log', 'safe'),
			array('profile_id, to, creation_date, message, log', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, profile_id, to, creation_date, message, log', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'profile_id' => Yii::t('app', 'Profile'),
			'to' => Yii::t('app', 'To'),
			'creation_date' => Yii::t('app', 'Creation Date'),
			'message' => Yii::t('app', 'Message'),
			'log' => Yii::t('app', 'Log'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('profile_id', $this->profile_id);
		$criteria->compare('to', $this->to, true);
		$criteria->compare('creation_date', $this->creation_date, true);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('log', $this->log, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}